# Generated by Django 4.2 on 2023-04-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_specificationcategory_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='vehiclespecification',
            old_name='specification_id',
            new_name='specification',
        ),
        migrations.RenameField(
            model_name='vehiclespecification',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
