# Generated by Django 4.2 on 2023-04-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_gal', models.DecimalField(decimal_places=3, max_digits=8)),
                ('total', models.DecimalField(decimal_places=3, max_digits=8)),
                ('missed_fill', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Fuel',
            },
        ),
    ]
